#' Load data from a URL into R with caching and sha1 version checking
#'
#' \code{source_data} loads data from a URL into R with caching and sha1
#' version checking.
#' @param url Character string of the file's URL.
#' @param sha1 Character string of the file's SHA-1 hash, generated by
#' \code{source_data}. Note if you are using data stored using Git, this is not
#' the file's commit SHA-1 hash.
#' @param cache logical. Whether or not to cache the data so that it is not
#' downloaded every time the function is called.
#' @param clearCache logical. Whether or not to clear the downloaded data from
#' the cache.
#' @param rdata Depricated.
#' @param ... additional arguments passed to \code{\link{import}}.
#'
#' @return a data frame
#'
#' @details Loads plain-text data (e.g. CSV, TSV) or RDATA from a URL. Works with
#' both HTTP and HTTPS sites. Note: the URL you give for the \code{url} argument
#' must be for the RAW version of the file. The function should work to download
#' plain-text data from any secure URL (https), though I have not verified this.
#'
#' From the \code{source_url} documentation: "If a SHA-1 hash is specified with
#' the \code{sha1} argument, then this function will check the SHA-1 hash of the
#' downloaded file to make sure it matches the expected value, and throw an error
#' if it does not match. If the SHA-1 hash is not specified, it will print a
#' message displaying the hash of the downloaded file. The purpose of this is to
#'  improve security when running remotely-hosted code; if you have a hash of
#' the file, you can be sure that it has not changed."
#'
#' @examples
#' \dontrun{
#' # Download electoral disproportionality data stored on GitHub
#' # Note: Using shortened URL created by bitly
#' DisData <- source_data("http://bit.ly/156oQ7a")
#'
#' # Check to see if SHA-1 hash matches downloaded file
#' DisDataHash <- source_data("http://bit.ly/Ss6zDO",
#'    sha1 = "dc8110d6dff32f682bd2f2fdbacb89e37b94f95d")
#' }
#' @seealso \link{import}.
#' @importFrom rio import
#' @importFrom digest digest
#' @importFrom R.cache saveCache loadCache findCache
#' @export

source_data <- function(
                    url,
                    sha1 = NULL,
                    cache = FALSE,
                    clearCache = FALSE,
                    rdata,
                    ...)
{


    # Compatability with version 0.4
    if (!missing(rdata)) message('rdata argument is deprecated. No longer needed.\n')


    stopifnot(is.character(url), length(url) == 1)

    temp_file <- tempfile()
    on.exit(unlink(temp_file))

    key <- as.list(url)
    if (isTRUE(clearCache)) {
        Found <- findCache(key = key)
        if (is.null(Found)) {
            message('Data not in cache. Nothing to remove.')
        }
        else if (!is.null(Found)) {
            message('Clearing data from cache.\n')
            file.remove(Found)
        }
    }

    if (isTRUE(cache)) {
        data <- loadCache(key)
        if (!is.null(data)) {
            message('Loading cached data.\n')
            return(data);
        }
        data <- download_data_intern(url = url, sha1 = sha1,
                                    temp_file = temp_file)
        data <- import(data, ...)
        saveCache(data, key = key)
        data;
    }
    else if (!isTRUE(cache)) {
        data <- download_data_intern(url = url, sha1 = sha1,
                                    temp_file = temp_file)
        data <- import(data, ...)
        return(data)
    }
}
